# Generated by Django 4.1.5 on 2024-07-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_project_tag_projectimage_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.FileField(upload_to='project_images/'),
        ),
    ]
