# Generated by Django 5.1.1 on 2024-10-19 18:35

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_userprofile_github_userprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='image',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='project_images/'),
        ),
    ]
